### PR TITLE
Add guide for Windows users to README

### PR DESCRIPTION
**Pull request by NORXND**
The guide is based on a solution found by me in #8 
I've tried my best to describe it so everybody will understand, I also checked it with grammar-check software to make sure it doesn't contain any typo.

The only thing I'm unsure about is how much space these tools needs, but as far as I know it is about 6GB.

### CODE REVIEW

**Review by long2ice — APPROVED** [review]

**Comment by long2ice** [comment]
Thanks! That's awesome.

**Comment by NORXND** [comment]
If you want, I can also provide already-built wheels. Of course, if you are not afraid of it.

**Comment by long2ice** [comment]
Maybe we can improve https://github.com/long2ice/asyncmy/blob/dev/.github/workflows/pypi.yml to build wheels automatically?

**Comment by NORXND** [comment]
> Maybe we can improve https://github.com/long2ice/asyncmy/blob/dev/.github/workflows/pypi.yml to build wheels automatically?

@long2ice Would be way better and all kinds of forks could work!

Once Ill finish school I will look into it.

**Comment by long2ice** [comment]
Thanks!

**Comment by NORXND** [comment]
@long2ice For now I have tried this
```yml
  publish_win:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Install and configure Poetry
        uses: snok/install-poetry@v1.1.1
        with:
          virtualenvs-create: false
      - name: Build dists
        run: make build
```

But it looks like it fails on `Build dists`

```shell
**Run make build
  make build
  shell: C:\Program Files\PowerShell\7\pwsh.EXE -command ". '{0}'"
  env:
    pythonLocation: C:\hostedtoolcache\windows\Python\3.9.7\x64
    VENV: .venv/scripts/activate
process_begin: CreateProcess(D:\a\asyncmy\asyncmy\poetry, poetry install, ...) failed.
make (e=193): Error 193
mingw32-make: *** [Makefile:10: deps] Error 193
Error: Process completed with exit code 1.**
```

I know you don't use Windows and I, sadly, never used all these building stuff like Poetry but I will look deeper into it.

Currently Im working here [here](https://github.com/NORXND/asyncmy/tree/winwheeltests)

**Pull request merged**
